services:   # Aquí empiezan a definirse los componentes (contenedores) del sistema.

  # --- INFRAESTRUCTURA DE MENSAJERÍA ---
  zookeeper:  # Nombre de nuestro primer servicio.
    image: confluentinc/cp-zookeeper:7.5.0 # La "receta" (imagen) que Docker descargará de internet.
    container_name: zookeeper
    environment: # Variables de configuración para que el contenedor sepa cómo comportarse.
      ZOOKEEPER_CLIENT_PORT: 2181 # Define el puerto interno en docker por el que Kafka se comunicará con él.

  kafka:      # Nombre de nuestro segundo servicio: el Broker.
    image: confluentinc/cp-kafka:7.5.0 # Imagen oficial de Confluent (una versión profesional de Kafka).
    container_name: kafka
    depends_on: # Regla de orden: no arranques Kafka hasta que ZooKeeper esté listo.
      zookeeper:
        condition: service_started
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports: # Mapeo de puertos: "Puerto en tu PC : Puerto dentro del contenedor".
      - "9092:9092" 
    environment: # Configuración crítica del Broker:
      KAFKA_BROKER_ID: 1 # ID único de este Broker dentro del cluster.
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Dirección donde el Broker encuentra al gerente (ZooKeeper).
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Cómo se conectarán tus aplicaciones al Broker.
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Como solo tenemos un broker, no podemos replicar (1 significa sin copia).
    volumes:
      - kafka_data:/var/lib/kafka/data

   # --- GOBIERNO Y GESTIÓN --> Gobierno de datos ---
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      # Intenta hacer un GET al endpoint de estado del registro
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"


  kafka-connect:
    # build: .
    # image: confluentinc/cp-kafka-connect:7.5.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 60s
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-cluster-flights
      # Tópicos internos que usa Kafka Connect para guardar su propia configuración
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      # Conversores de formato para la clave y el valor del mensaje
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      # CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"  
      CONNECT_PLUGIN_PATH: "/usr/share/java/camel-connectors"  
   


  # --- BBDD ---
  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck: # PETICION DE SALUD (si responde correctamente)
      test: ["CMD-SHELL", "pg_isready -U admin -d transacciones_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: transacciones_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d #link con scripts .sql para creacion de tablas de bbdd


# VOLUMENES
volumes:
  kafka_data:
  postgres_data:   

