FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install requests beautifulsoup4 pandas


COPY _data/scraper/scraper.py .
RUN mkdir -p /app/output
CMD ["python", "scraper.py"]