FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY schemas/ /app/schemas/
COPY src/dic_rutas /app/src/dic_rutas

CMD ["python", "src/dic_rutas/dic_rutas.py"]